[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["jdk21"]

[build.nixpacksPlan.phases.build]
cmds = ["cd backend-springboot && ./mvnw clean package -DskipTests"]

[build.nixpacksPlan.start]
cmd = "java -Dserver.port=$PORT -jar backend-springboot/target/backend-0.0.1-SNAPSHOT.jar"
