[build]
builder = "nixpacks"
nixpacksPlan = """
[phases.setup]
nixPkgs = ['jdk21']

[phases.build]
cmds = ['cd backend-springboot && ./mvnw clean package -DskipTests']

[start]
cmd = 'java -Dserver.port=$PORT -jar backend-springboot/target/backend-0.0.1-SNAPSHOT.jar'
"""
