[build]
buildCommand = "cd backend-springboot && chmod +x mvnw && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar backend-springboot/target/backend-0.0.1-SNAPSHOT.jar"
