[build]
builder = "nixpacks"
buildCommand = "cd backend-springboot && mvn clean package -DskipTests"

[deploy]
startCommand = "cd backend-springboot && java -Dserver.port=$PORT -jar target/backend-0.0.1-SNAPSHOT.jar"

